import { User, Task } from './types';
import { subMonths, subDays, addHours } from 'date-fns';
import { Timestamp } from 'firebase/firestore';

// Note: This mock data is for reference. The app will use live data from Firestore.
// We are converting Date objects to Timestamps to maintain consistency with Firestore's data format.

const toTimestamp = (date: Date): Timestamp => Timestamp.fromDate(date);
const now = new Date();

export const mockUsers: User[] = [
  {
    uid: 'admin1',
    email: 'admin@cveezy.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: toTimestamp(new Date()),
    isActive: true,
  },
  {
    uid: 'mod1',
    email: 'moderator@cveezy.com',
    name: 'Moderator Ali',
    role: 'moderator',
    createdAt: toTimestamp(new Date()),
    isActive: true,
    photoURL: 'https://picsum.photos/seed/mod1/100/100'
  },
  {
    uid: 'designer1',
    email: 'designer1@cveezy.com',
    name: 'Designer Fatima',
    role: 'designer',
    createdAt: toTimestamp(new Date()),
    isActive: true,
  },
  {
    uid: 'designer2',
    email: 'designer2@cveezy.com',
    name: 'Designer Omar',
    role: 'designer',
    createdAt: toTimestamp(new Date()),
    isActive: true,
  },
  {
    uid: 'client1',
    email: 'client1@example.com',
    name: 'Client Ahmed',
    role: 'client',
    createdAt: toTimestamp(new Date()),
    isActive: true,
  },
];


export const mockTasks: Omit<Task, 'id'>[] = [
  {
    taskId: '1700000000001',
    clientName: 'Nour Mohamed',
    clientPhone: '01012345678',
    services: [{ type: 'سيرة ذاتية (ATS)', language: 'إنجليزي', deliveryTime: '48 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 500,
    financialPaid: 500,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subDays(now, 5)),
    updatedAt: toTimestamp(subDays(now, 2)),
    completedAt: toTimestamp(subDays(now, 2)),
    dueDate: toTimestamp(addHours(subDays(now, 5), 48)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subDays(now, 5)),
  },
  {
    taskId: '1700000000002',
    clientName: 'Youssef Hassan',
    clientPhone: '01123456789',
    services: [{ type: 'تحسين بروفايل لينكدإن', language: 'عربي', deliveryTime: '72 ساعة' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'in_progress',
    financialTotal: 300,
    financialPaid: 150,
    financialRemaining: 150,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subDays(now, 3)),
    updatedAt: toTimestamp(subDays(now, 1)),
    dueDate: toTimestamp(addHours(subDays(now, 3), 72)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subDays(now, 3)),
  },
  {
    taskId: '1700000000003',
    clientName: 'Mariam Adel',
    clientPhone: '01234567890',
    services: [{ type: 'سيرة ذاتية (Standard)', language: 'ثنائي (ع+E)', deliveryTime: '24 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'to_review',
    financialTotal: 400,
    financialPaid: 400,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subDays(now, 1)),
    updatedAt: toTimestamp(now),
    dueDate: toTimestamp(addHours(subDays(now, 1), 24)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subDays(now, 1)),
  },
  {
    taskId: '1700000000004',
    clientName: 'Khaled Said',
    clientPhone: '01545678901',
    services: [{ type: 'سيرة ذاتية (ATS)', language: 'إنجليزي', deliveryTime: '6 ساعات' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'new',
    financialTotal: 600,
    financialPaid: 300,
    financialRemaining: 300,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(now),
    updatedAt: toTimestamp(now),
    dueDate: toTimestamp(addHours(now, 6)),
    createdBy: 'mod1',
    taskDate: toTimestamp(now),
  },
  {
    taskId: '1700000000005',
    clientName: 'Fatma Ali',
    clientPhone: '01067890123',
    services: [{ type: 'بورتفوليو أعمال', language: 'إنجليزي', deliveryTime: '72 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 1200,
    financialPaid: 1200,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subDays(now, 10)),
    updatedAt: toTimestamp(subDays(now, 6)),
    completedAt: toTimestamp(subDays(now, 6)),
    dueDate: toTimestamp(addHours(subDays(now, 10), 72)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subDays(now, 10)),
  },
    {
    taskId: '1700000000007',
    clientName: 'Sherine Abdel-Wahab',
    clientPhone: '01232109876',
    services: [{ type: 'تعديل/تحسين السيرة', language: 'إنجليزي', deliveryTime: '12 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'in_progress',
    financialTotal: 250,
    financialPaid: 250,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subDays(now, 1)),
    updatedAt: toTimestamp(now),
    dueDate: toTimestamp(addHours(subDays(now, 1), 12)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subDays(now, 1)),
  },
  {
    taskId: '1700000000008',
    clientName: 'Tamer Hosny',
    clientPhone: '01587654321',
    services: [{ type: 'سيرة ذاتية (ATS)', language: 'إنجليزي', deliveryTime: '24 ساعة' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 500,
    financialPaid: 500,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subMonths(now, 1)),
    updatedAt: toTimestamp(subMonths(now, 1)),
    completedAt: toTimestamp(subDays(subMonths(now, 1), 2)),
    dueDate: toTimestamp(addHours(subMonths(now, 1), 24)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subMonths(now, 1)),
  },
    {
    taskId: '1700000000009',
    clientName: 'Nancy Ajram',
    clientPhone: '01000000009',
    services: [{ type: 'سيرة ذاتية (Standard)', language: 'فرنسي', deliveryTime: '72 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 90,
    financialPaid: 90,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subDays(now, 4)),
    updatedAt: toTimestamp(subDays(now, 1)),
    completedAt: toTimestamp(subDays(now, 1)),
    dueDate: toTimestamp(addHours(subDays(now, 4), 72)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subDays(now, 4)),
  },
  {
    taskId: '1700000000010',
    clientName: 'Elissa Khoury',
    clientPhone: '01111111110',
    services: [{ type: 'تحسين بروفايل لينكدإن', language: 'إنجليزي', deliveryTime: '48 ساعة' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 350,
    financialPaid: 350,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subMonths(now, 1)),
    updatedAt: toTimestamp(subDays(subMonths(now, 1), 5)),
    completedAt: toTimestamp(subDays(subMonths(now, 1), 5)),
    dueDate: toTimestamp(addHours(subMonths(now, 1), 48)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subMonths(now, 1)),
  },
    {
    taskId: '1700000000011',
    clientName: 'Haifa Wehbe',
    clientPhone: '01222222211',
    services: [{ type: 'سيرة ذاتية بنمط Europass', language: 'إنجليزي', deliveryTime: '24 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'new',
    financialTotal: 400,
    financialPaid: 0,
    financialRemaining: 400,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subDays(now, 0)),
    updatedAt: toTimestamp(subDays(now, 0)),
    dueDate: toTimestamp(addHours(now, 24)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subDays(now, 0)),
  },
  {
    taskId: '1700000000012',
    clientName: 'Kadim Al Sahir',
    clientPhone: '01555555512',
    services: [{ type: 'سيرة ذاتية (Standard)', language: 'عربي', deliveryTime: '3 ساعات' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'in_progress',
    financialTotal: 700,
    financialPaid: 700,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: toTimestamp(subHours(now, 1)),
    updatedAt: toTimestamp(subHours(now, 0)),
    dueDate: toTimestamp(addHours(subHours(now, 1), 3)),
    createdBy: 'mod1',
    taskDate: toTimestamp(subHours(now, 1)),
  },
];
