import { User, Task, Experience, Service } from './types';
import { subMonths, subDays, addHours } from 'date-fns';

export const mockUsers: User[] = [
  {
    uid: 'admin1',
    email: 'admin@cveezy.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: new Date(),
    isActive: true,
  },
  {
    uid: 'mod1',
    email: 'moderator@cveezy.com',
    name: 'Moderator Ali',
    role: 'moderator',
    createdAt: new Date(),
    isActive: true,
    photoURL: 'https://picsum.photos/seed/mod1/100/100'
  },
  {
    uid: 'designer1',
    email: 'designer1@cveezy.com',
    name: 'Designer Fatima',
    role: 'designer',
    createdAt: new Date(),
    isActive: true,
  },
  {
    uid: 'designer2',
    email: 'designer2@cveezy.com',
    name: 'Designer Omar',
    role: 'designer',
    createdAt: new Date(),
    isActive: true,
  },
  {
    uid: 'client1',
    email: 'client1@example.com',
    name: 'Client Ahmed',
    role: 'client',
    createdAt: new Date(),
    isActive: true,
  },
];

const now = new Date();

export const mockTasks: Task[] = [
  {
    id: 'task1',
    taskId: '1700000000001',
    clientName: 'Nour Mohamed',
    clientPhone: '01012345678',
    services: [{ type: 'سيرة ذاتية (ATS)', language: 'إنجليزي', deliveryTime: '48 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 500,
    financialPaid: 500,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 5),
    updatedAt: subDays(now, 2),
    completedAt: subDays(now, 2),
    dueDate: addHours(subDays(now, 5), 48),
    createdBy: 'mod1',
    taskDate: subDays(now, 5),
  },
  {
    id: 'task2',
    taskId: '1700000000002',
    clientName: 'Youssef Hassan',
    clientPhone: '01123456789',
    services: [{ type: 'تحسين بروفايل لينكدإن', language: 'عربي', deliveryTime: '72 ساعة' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'in_progress',
    financialTotal: 300,
    financialPaid: 150,
    financialRemaining: 150,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 3),
    updatedAt: subDays(now, 1),
    dueDate: addHours(subDays(now, 3), 72),
    createdBy: 'mod1',
    taskDate: subDays(now, 3),
  },
  {
    id: 'task3',
    taskId: '1700000000003',
    clientName: 'Mariam Adel',
    clientPhone: '01234567890',
    services: [{ type: 'سيرة ذاتية (Standard)', language: 'ثنائي (ع+E)', deliveryTime: '24 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'to_review',
    financialTotal: 400,
    financialPaid: 400,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 1),
    updatedAt: now,
    dueDate: addHours(subDays(now, 1), 24),
    createdBy: 'mod1',
    taskDate: subDays(now, 1),
  },
  {
    id: 'task4',
    taskId: '1700000000004',
    clientName: 'Khaled Said',
    clientPhone: '01545678901',
    services: [{ type: 'سيرة ذاتية (ATS)', language: 'إنجليزي', deliveryTime: '6 ساعات' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'new',
    financialTotal: 600,
    financialPaid: 300,
    financialRemaining: 300,
    financialCurrency: 'EGP',
    createdAt: now,
    updatedAt: now,
    dueDate: addHours(now, 6),
    createdBy: 'mod1',
    taskDate: now,
  },
  {
    id: 'task5',
    taskId: '1700000000005',
    clientName: 'Fatma Ali',
    clientPhone: '01067890123',
    services: [{ type: 'بورتفوليو أعمال', language: 'إنجليزي', deliveryTime: '72 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 1200,
    financialPaid: 1200,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 10),
    updatedAt: subDays(now, 6),
    completedAt: subDays(now, 6),
    dueDate: addHours(subDays(now, 10), 72),
    createdBy: 'mod1',
    taskDate: subDays(now, 10),
  },
  {
    id: 'task6',
    taskId: '1700000000006',
    clientName: 'Amr Diab',
    clientPhone: '01198765432',
    services: [{ type: 'سيرة ذاتية بنمط الخليج', language: 'عربي', deliveryTime: '48 ساعة' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'overdue',
    financialTotal: 450,
    financialPaid: 200,
    financialRemaining: 250,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 4),
    updatedAt: subDays(now, 1),
    dueDate: addHours(subDays(now, 4), 48), // This due date is in the past
    createdBy: 'mod1',
    taskDate: subDays(now, 4),
  },
  {
    id: 'task7',
    taskId: '1700000000007',
    clientName: 'Sherine Abdel-Wahab',
    clientPhone: '01232109876',
    services: [{ type: 'تعديل/تحسين السيرة', language: 'إنجليزي', deliveryTime: '12 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'in_progress',
    financialTotal: 250,
    financialPaid: 250,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 1),
    updatedAt: now,
    dueDate: addHours(subDays(now, 1), 12),
    createdBy: 'mod1',
    taskDate: subDays(now, 1),
  },
  {
    id: 'task8',
    taskId: '1700000000008',
    clientName: 'Tamer Hosny',
    clientPhone: '01587654321',
    services: [{ type: 'سيرة ذاتية (ATS)', language: 'إنجليزي', deliveryTime: '24 ساعة' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 500,
    financialPaid: 500,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subMonths(now, 1),
    updatedAt: subMonths(now, 1),
    completedAt: subDays(subMonths(now, 1), 2),
    dueDate: addHours(subMonths(now, 1), 24),
    createdBy: 'mod1',
    taskDate: subMonths(now, 1),
  },
    {
    id: 'task9',
    taskId: '1700000000009',
    clientName: 'Nancy Ajram',
    clientPhone: '01000000009',
    services: [{ type: 'سيرة ذاتية (Standard)', language: 'فرنسي', deliveryTime: '72 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 90,
    financialPaid: 90,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 4),
    updatedAt: subDays(now, 1),
    completedAt: subDays(now, 1),
    dueDate: addHours(subDays(now, 4), 72),
    createdBy: 'mod1',
    taskDate: subDays(now, 4),
  },
  {
    id: 'task10',
    taskId: '1700000000010',
    clientName: 'Elissa Khoury',
    clientPhone: '01111111110',
    services: [{ type: 'تحسين بروفايل لينكدإن', language: 'إنجليزي', deliveryTime: '48 ساعة' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'done',
    financialTotal: 350,
    financialPaid: 350,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subMonths(now, 1),
    updatedAt: subDays(subMonths(now, 1), 5),
    completedAt: subDays(subMonths(now, 1), 5),
    dueDate: addHours(subMonths(now, 1), 48),
    createdBy: 'mod1',
    taskDate: subMonths(now, 1),
  },
    {
    id: 'task11',
    taskId: '1700000000011',
    clientName: 'Haifa Wehbe',
    clientPhone: '01222222211',
    services: [{ type: 'سيرة ذاتية بنمط Europass', language: 'إنجليزي', deliveryTime: '24 ساعة' }],
    designerId: 'designer1',
    moderatorId: 'mod1',
    status: 'new',
    financialTotal: 400,
    financialPaid: 0,
    financialRemaining: 400,
    financialCurrency: 'EGP',
    createdAt: subDays(now, 0),
    updatedAt: subDays(now, 0),
    dueDate: addHours(now, 24),
    createdBy: 'mod1',
    taskDate: subDays(now, 0),
  },
  {
    id: 'task12',
    taskId: '1700000000012',
    clientName: 'Kadim Al Sahir',
    clientPhone: '01555555512',
    services: [{ type: 'سيرة ذاتية (Standard)', language: 'عربي', deliveryTime: '3 ساعات' }],
    designerId: 'designer2',
    moderatorId: 'mod1',
    status: 'in_progress',
    financialTotal: 700,
    financialPaid: 700,
    financialRemaining: 0,
    financialCurrency: 'EGP',
    createdAt: subHours(now, 1),
    updatedAt: subHours(now, 0),
    dueDate: addHours(subHours(now, 1), 3),
    createdBy: 'mod1',
    taskDate: subHours(now, 1),
  },
];
